cargo-features = ["edition2024"]
[package]
name = "first-rg-shader"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { workspace = true }

bytemuck = { version = "1.18.0", features = ["derive"] }
