[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-Zshare-generics=off"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-Zshare-generics=off"]
runner = "python bld-deploy-remote.py -t -r --source"
