cargo-features = ["edition2024"]

[package]
name = "program-wgpu-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { version = "23", features = ["spirv", "vulkan-portability"]}
winit = { version = "0.30.0", features = ["android-native-activity", "rwh_05"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
shared = { path = "../shared" }
rand = "0.9.0"
glam = { version = "0.29.2", features = ["bytemuck"] }

[build-dependencies]
spirv-builder = { workspace = true }
