cargo-features = ["edition2024"]

[package]
name = "program-wgpu-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { version = "23", features = ["spirv", "vulkan-portability"]}
winit = { version = "0.30.0", features = ["android-native-activity", "rwh_05"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
shared = { path = "../shared" }
rand = "0.9.0"

egui = "0.29.1"
raw-window-handle = "0.6.2"
egui-wgpu = { version = "0.29.1",features = ["winit"] }
egui-winit = "0.29.1"
pollster = "0.3.0"


[build-dependencies]
#spirv-builder = { workspace = true }
